import subprocess
import time
from pathlib import Path
from datetime import datetime
import sys

sys.path.append(str(Path(__file__).parent.parent))
from config.ai_config import AIEngine

class Orchestrator:
    def __init__(self, vault_path):
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / 'Needs_Action'
        self.plans = self.vault_path / 'Plans'
        self.done = self.vault_path / 'Done'
        self.check_interval = 30  # 30 seconds
        
    def check_pending_tasks(self):
        """Check if there are files in Needs_Action"""
        tasks = list(self.needs_action.glob('*.md'))
        return len(tasks)
    
    def trigger_claude(self):
        """Trigger AI to process tasks"""
        print(f"\n🤖 AI processing tasks...")
        
        try:
            ai = AIEngine()
            
            # Process each task
            for task_file in self.needs_action.glob('*.md'):
                print(f"📄 Processing: {task_file.name}")
                
                task_content = task_file.read_text(encoding='utf-8')
                plan = ai.process_task(task_content)
                
                # Create plan
                plan_file = self.plans / f"PLAN_{task_file.stem}.md"
                plan_file.write_text(f"""# Plan: {task_file.stem}

{plan}

---
Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
""", encoding='utf-8')
                
                # Move to done
                task_file.rename(self.done / task_file.name)
                print(f"✅ Done: {task_file.name}")
                
        except Exception as e:
            print(f"❌ Error: {e}")
        
    def update_dashboard(self):
        """Update dashboard with stats"""
        dashboard = self.vault_path / 'Dashboard.md'
        pending = len(list(self.needs_action.glob('*.md')))
        plans = len(list(self.plans.glob('*.md')))
        done = len(list(self.done.glob('*.md')))
        
        content = f"""# AI Employee Dashboard

## Today's Overview
Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

### Pending Tasks
- {pending} tasks in queue

### Active Plans
- {plans} plans created

### Completed
- {done} tasks done today

### Business Metrics
- Revenue MTD: $0
- Active Projects: 0
- Pending Approvals: 0

---
*Auto-generated by AI Employee*
"""
        dashboard.write_text(content, encoding='utf-8')
        
    def run(self):
        print("🚀 Orchestrator started...")
        print(f"📊 Vault: {self.vault_path}")
        
        while True:
            try:
                pending = self.check_pending_tasks()
                
                if pending > 0:
                    print(f"\n📋 Found {pending} pending task(s)")
                    self.trigger_claude()
                
                self.update_dashboard()
                time.sleep(self.check_interval)
                
            except KeyboardInterrupt:
                print("\n⏹️  Orchestrator stopped")
                break

if __name__ == "__main__":
    vault = Path(__file__).parent.parent / 'vault'
    orchestrator = Orchestrator(vault)
    orchestrator.run()